# Generated by Django 2.2.11 on 2020-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200329_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='videotag',
            unique_together={('video', 'tag')},
        ),
    ]
